name: AI PR Review

on:
  pull_request:
    types: [opened, labeled]
    branches: [master, main]

  workflow_dispatch: 
    inputs: 
        ref:
          description: 'Branch or commit SHA to review'
          required: false
          default: 'master'
        pr: 
            description: 'Pull request number to review'
            required: false
            type: number

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AI PR Review
        uses: stillrivercode/stillriver-ai-workflows@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
          model: ${{ vars.AI_MODEL || 'google/gemini-2.5-pro' }}
          review_type: 'full'
          max_tokens: 32768
          temperature: 0.3
          exclude_patterns: '.github/*, *.json'
          custom_review_rules: 'custom-rules/review.json'