name: AI PR Review

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches: [master, main]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    if: |
      (github.event.pull_request.base.ref == 'master' || github.event.pull_request.base.ref == 'main') &&
      (
        github.event.action == 'opened' ||
        github.event.action == 'reopened' ||
        github.event.action == 'synchronize' ||
        (github.event.action == 'labeled' && github.event.label.name == 'needs-ai-review')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: AI PR Review
        uses: stillrivercode/stillriver-ai-workflows@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
          model: ${{ vars.AI_MODEL || 'google/gemini-2.5-pro' }}
          review_type: 'full'
          max_tokens: 32768
          temperature: 0.3
          custom_review_rules: 'custom-rules/review.json'
      # ────────────── LABEL MAINTENANCE ──────────────
      # 1. Drop the “needs-ai-review” label if it exists
      - name: Remove needs-ai-review label (if present)
        if: |
          contains(
            join(github.event.pull_request.labels.*.name, ','),
            'needs-ai-review'
          )
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: needs-ai-review

      # 2. Add / ensure the “ai-reviewed” label
      - name: Add ai-reviewed label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ai-reviewed